#!/bin/sh

yabai -m query --windows --space |awk -F: '
    function swap_windows(i, j, tmp) {
        tmp = window_ids[i];
        window_ids[i] = window_ids[j];
        window_ids[j] = tmp;
    }
    function sort_windows(i, j, delta) {
        for (i = 0; i < window_count; i++) {
            for (j = i+1; j < window_count; j++) {
                delta = windows[window_ids[j],"x"] - windows[window_ids[i],"x"];
                if (delta < 0)
                    swap_windows(i, j);
                else if (delta == 0) {
                    delta = windows[window_ids[j],"y"] - windows[window_ids[i],"y"];
                    if (delta > 0)
                        swap_windows(i, j);
                }
            }
        }
    }
    BEGIN{
        window_count = 0;
    }
    {
        gsub(/[," \t]/, "", $0);
    }
    $1 == "id" {
        window_id = $2;
        window_ids[window_count] = window_id;
        window_count++;
    }
    $1 == "x"     { windows[window_id,"x"] = $2; }
    $1 == "y"     { windows[window_id,"y"] = $2; }
    $1 == "w"     { windows[window_id,"w"] = $2; }
    $1 == "h"     { windows[window_id,"h"] = $2; }
    $1 == "space" { windows[window_id,"space"] = $2; }
    END{
        sort_windows();
        cmdline = "";
        for (i in window_ids) {
            window_id = window_ids[i];
            cmdline = cmdline sprintf(" %d,%s,%s,%s,%s,%s",
                                      windows[window_id,"space"],
                                      windows[window_id,"x"],
                                      windows[window_id,"y"],
                                      windows[window_id,"w"],
                                      windows[window_id,"h"],
                                      i);
        }
        print cmdline;
    }

'
